### ISSUE TITLE
getPartitions fails with SimpleRequestFactory

### ISSUE THREAD

**Issue by vporoshin** [zalando-nakadi/fahrschein#193]
calling ```nakadiClient.getPartitions("some-existing-event-type")``` fails with the following exception (for ```0.13.0``` version)

```
cannot write to a URLConnection if doOutput=false - call setDoOutput(true)
java.net.ProtocolException: cannot write to a URLConnection if doOutput=false - call setDoOutput(true)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1298)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1291)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1500)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at org.zalando.fahrschein.http.simple.SimpleBufferingRequest.executeInternal(SimpleBufferingRequest.java:88)
	at org.zalando.fahrschein.http.simple.SimpleBufferingRequest.execute(SimpleBufferingRequest.java:113)
	at org.zalando.fahrschein.ProblemHandlingRequest.execute(ProblemHandlingRequest.java:31)
	at org.zalando.fahrschein.NakadiClient.getPartitions(NakadiClient.java:57)
```

example program: 
```scala
import java.net.URI
import org.scalatest.FlatSpec
import org.zalando.fahrschein.http.simple.SimpleRequestFactory
import org.zalando.fahrschein.{ManagedCursorManager, NakadiClient, ZignAccessTokenProvider}

class FahrscheinTest extends FlatSpec {

  it should "test getPartitions failure" in {

    val nakadiUrl = URI.create("https://nakadi-server")
    val accessTokenProvider = new ZignAccessTokenProvider
    val requestFactory = new SimpleRequestFactory

    val nakadiClient = NakadiClient.builder(nakadiUrl)
      .withRequestFactory(requestFactory)
      .withAccessTokenProvider(accessTokenProvider)
      .withCursorManager(new ManagedCursorManager(nakadiUrl, requestFactory, accessTokenProvider))
      .build()

    nakadiClient.getPartitions("some-existing-event-type")
  }

}
```

**Comment by jhorstmann** [comment]
Thanks for the detailed report, it seems this bug was introduced in #190. Staying with release 0.12.0 should be fine until the fix is released.
