### ISSUE TITLE
Add details to IOProblem when comitting the cursor fails

### ISSUE THREAD

**Issue by Gregsen** [zalando-nakadi/fahrschein#229]
When there is an issue with committing the cursor, a the response is [parsed](https://github.com/zalando-nakadi/fahrschein/blob/master/fahrschein/src/main/java/org/zalando/fahrschein/ProblemHandlingRequest.java#L48) but not always shown in the logs.
Maybe the parsed responseBody can be added as [details](https://github.com/zalando-nakadi/fahrschein/blob/master/fahrschein/src/main/java/org/zalando/fahrschein/IOProblem.java#L28) (when the reponse does not pass the checks before) in [line 57](https://github.com/zalando-nakadi/fahrschein/blob/master/fahrschein/src/main/java/org/zalando/fahrschein/IOProblem.java#L28).
As a concrete example, we had an operation that took longer than 60 seconds and so we were over the commit time for the stream. The Response from Nakadi was `org.zalando.fahrschein.IOProblem: Problem [about:blank] with status [422]: [Unprocessable Entity] []` and only via Breakpoint we were able to see the errror message from Nakdi.

**Comment by jhorstmann** [comment]
Do you by any chance still have the original response including its content type header? The way I understand the code, the details should have been added to the thrown IOProblem, given the correct content type and and required type and title attributes. The stack trace could also be helpful.

**Comment by Gregsen** [comment]
Sure. This is the request:
```
sun.net.www.MessageHeader@7a761e6a9 pairs: {POST /subscriptions/1324578-1324-4567-aabb-a3f5e365dd12/cursors HTTP/1.1: null}{Authorization: Bearer myToken}{Content-Type: application/json}{X-Nakadi-StreamId: 8e43ce03-069d-4f83-b94a-6a280cae52e1}{User-Agent: Java/1.8.0_191}{Host: nakadi.example.com}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}{Content-Length: 158}
```
The Reponse header:
```
{Server=[nginx/1.14.0], 
Date=[Thu, 18 Apr 2019 10:44:51 GMT], 
Content-Type=[application/problem+json], 
Transfer-Encoding=[chunked], 
Connection=[keep-alive], 
X-Flow-Id=[myFlowID], 
X-Application-Context=[application:8080], 
X-Content-Type-Options=[nosniff], 
X-XSS-Protection=[1; mode=block], 
Cache-Control=[no-cache, no-store, max-age=0, must-revalidate], 
Pragma=[no-cache], 
Expires=[0], 
X-Frame-Options=[DENY]}
```
The parsed response body:
```
{"title":"Unprocessable Entity","status":422,"detail":"Session with stream id 8e43ce03-069d-4f83-b94a-6a280cae52e1 not found"}
```

Stacktrace
```
2019-04-18 12:33:54.736  WARN 20050 --- [pool-1-thread-1] org.zalando.fahrschein.NakadiReader      : Exception while processing events for [events.my-event] on partition [0] at offset [001-0005-000000000000000736]

org.zalando.fahrschein.IOProblem: Problem [about:blank] with status [422]: [Unprocessable Entity] []
	at org.zalando.fahrschein.ProblemHandlingRequest.execute(ProblemHandlingRequest.java:57) ~[fahrschein-0.16.0.jar:na]
	at org.zalando.fahrschein.ManagedCursorManager.onSuccess(ManagedCursorManager.java:125) ~[fahrschein-0.16.0.jar:na]
	at org.zalando.fahrschein.NakadiReader$2.run(NakadiReader.java:210) ~[fahrschein-0.16.0.jar:na]
	at org.zalando.fahrschein.DefaultBatchHandler.processBatch(DefaultBatchHandler.java:13) [fahrschein-0.16.0.jar:na]
	at org.zalando.fahrschein.NakadiReader.processBatch(NakadiReader.java:205) [fahrschein-0.16.0.jar:na]
	at org.zalando.fahrschein.NakadiReader.readBatch(NakadiReader.java:400) [fahrschein-0.16.0.jar:na]
	at org.zalando.fahrschein.NakadiReader.runInternal(NakadiReader.java:290) [fahrschein-0.16.0.jar:na]
	at org.zalando.fahrschein.NakadiReader.run(NakadiReader.java:266) [fahrschein-0.16.0.jar:na]
	at org.zalando.fahrschein.StreamBuilders$AbstractStreamBuilder.listen(StreamBuilders.java:57) [fahrschein-0.16.0.jar:na]
	at io.gregsen.communication.myApplication.data.event.AbstractConsumer.consume(AbstractConsumer.java:84) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) [spring-context-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_191]
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308) [na:1.8.0_191]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java) [na:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]
```

**Comment by jhorstmann** [comment]
Thanks, I see the problem now, fahrschein is trying to guess whether a response is in problem format based on the contents and [expects both a `title` and `type` property](https://github.com/zalando-nakadi/fahrschein/blob/f4bb5e4cef87574074c513e5171569fe91bb91f3/fahrschein/src/main/java/org/zalando/fahrschein/ProblemHandlingRequest.java#L84). Looking at the [RFC](https://tools.ietf.org/html/rfc7807.html#section-3.1) it seems the `type` property is actually optional, and indeed it's missing in this response.

If I remember correctly, the detection was done because some endpoints returned just `application/json` without problem subtype, and some errors from spring security are returned in a different format than problem. The fix could be to only treat the `title` property as required, so as long as there is a `title` property try to parse it as problem. Would you be interested in opening a pull request?

**Comment by Gregsen** [comment]
I would :). Shall I "just" change this or can I also fix some minor stuff (e.g. unused imports) along the way? Either way is fine with me

**Comment by jhorstmann** [comment]
Cleanups are of course appreciated. A testcase similar to [shouldDeserializeProblemJson](https://github.com/zalando-nakadi/fahrschein/blob/f4bb5e4cef87574074c513e5171569fe91bb91f3/fahrschein/src/test/java/org/zalando/fahrschein/ProblemHandlingRequestTest.java#L54) would also be very nice.
