### ISSUE TITLE
Offset commit timeout errors give no hints in the logs

### ISSUE THREAD

**Issue by othon2000** [zalando-nakadi/fahrschein#254]
(PR will follow)

According to the current Nakadi API:
```
        Endpoint for committing offsets of the subscription. If there is uncommited data, and no commits happen
        for 60 seconds, then Nakadi will consider the client to be gone, and will close the connection. As long
        as no events are sent, the client does not need to commit.
        If the connection is closed, the client has 60 seconds to commit the events it received, from the moment
        they were sent. After that, the connection will be considered closed, and it will not be possible to do
        commit with that `X-Nakadi-StreamId` anymore.
        When a batch is committed that also automatically commits all previous batches that were
        sent in a stream for this partition.
```
(source) https://github.com/zalando/nakadi/blob/e83f5f045c75a1bb3f37a74ab3a874b1e197529b/docs/_data/nakadi-event-bus-api.yaml#L1318

If we try to commit a cursor offset after 60 seconds, it will fail. In such cases, the following error message is produced by Fahrschein:
```
org.zalando.fahrschein.NakadiReader      : Exception while processing events for [xxx] on partition [3] at offset [yyy]
org.zalando.fahrschein.IOProblem: Problem [about:blank] with status [422]: [Unprocessable Entity] [Session with stream id zzz not found]
	at org.zalando.fahrschein.ProblemHandlingRequest.handleProblem(ProblemHandlingRequest.java:105) ~[fahrschein-0.18.0.jar!/:na]
	at org.zalando.fahrschein.ProblemHandlingRequest.execute(ProblemHandlingRequest.java:53) ~[fahrschein-0.18.0.jar!/:na]
	at org.zalando.fahrschein.ManagedCursorManager.onSuccess(ManagedCursorManager.java:124) ~[fahrschein-0.18.0.jar!/:na]
	at org.zalando.fahrschein.NakadiReader$2.run(NakadiReader.java:210) ~[fahrschein-0.18.0.jar!/:na]
	at org.zalando.fahrschein.DefaultBatchHandler.processBatch(DefaultBatchHandler.java:13) [fahrschein-0.18.0.jar!/:na]
	at org.zalando.fahrschein.NakadiReader.processBatch(NakadiReader.java:205) [fahrschein-0.18.0.jar!/:na]
	at org.zalando.fahrschein.NakadiReader.readBatch(NakadiReader.java:400) [fahrschein-0.18.0.jar!/:na]…(more)
```

It gives no hint to the application owner that there's a timeout happening. This ends up delaying the troubleshooting, which in such case can be simply reducing the batch size as a quick recovery measure.

Unfortunately, `HTTP 422` does not always mean a timeout. It can mean, for example, that the client is sending a non-existing stream ID. But the client can be better in the sense of hinting that timeout is a likely issue.

**Comment by othon2000** [comment]
Should be fixed from version `0.19.0`
